


services:
  fastapiapp:
    container_name: fastapiapp
    image: fastapiapp:1.0.0
    build:
      context: ./fastapi  # Points to the folder where your Dockerfile and code live
      dockerfile: fastapi.dockerfile  # You’ll create this file below
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
